import Foundation

public enum CleanCatalog {
    public static func standard(home: URL = FileManager.default.homeDirectoryForCurrentUser,
                                environment: [String: String] = ProcessInfo.processInfo.environment) -> [CleanRule] {
        let library = home.appendingPathComponent("Library")
        let caches = library.appendingPathComponent("Caches")
        let developer = library.appendingPathComponent("Developer")
        let xcode = developer.appendingPathComponent("Xcode")
        let homebrewCache = environment["HOMEBREW_CACHE"].map { URL(fileURLWithPath: $0) } ?? caches.appendingPathComponent("Homebrew")

        return [
            CleanRule(id: "app-caches", category: .caches, title: "App caches",
                      what: "Data apps keep to start faster: thumbnails, downloaded resources, compiled scripts. Only apps that are still installed are listed; caches of removed apps show up under Leftovers.",
                      why: "Apps build their cache again the next time they run. Caches of apps running right now are left unselected.",
                      paths: [caches], scope: .appOwned, kind: .caches),
            CleanRule(id: "app-logs", category: .logs, title: "App logs",
                      what: "Logs that third-party apps write about their own doings.",
                      why: "They only matter while you are chasing a problem in that app. The logs macOS keeps are not touched.",
                      paths: [library.appendingPathComponent("Logs")], scope: .appOwned, kind: .logs),
            CleanRule(id: "derived-data", category: .developer, title: "Xcode build folders",
                      what: "DerivedData: intermediate build products, indexes and module caches for every project opened in Xcode.",
                      why: "Xcode rebuilds them on the next build, which takes longer that one time.",
                      paths: [xcode.appendingPathComponent("DerivedData")], scope: .children, kind: .developer),
            CleanRule(id: "device-support", category: .developer, title: "Device support files",
                      what: "Debug symbols Xcode copied from each iPhone, iPad, Watch or Apple TV that was connected, one folder per OS version.",
                      why: "Folders for OS versions you no longer run are never used again. The current one Xcode copies back the next time the device is plugged in, which takes a few minutes, so pick the versions yourself.",
                      paths: ["iOS", "watchOS", "tvOS", "visionOS"].map { xcode.appendingPathComponent("\($0) DeviceSupport") },
                      scope: .children, kind: .developer, selectedByDefault: false),
            CleanRule(id: "archives", category: .developer, title: "Xcode archives",
                      what: "Archived builds, including the debug symbols needed to read crash reports from those builds.",
                      why: "Only safe for builds you no longer ship or need to symbolicate, so nothing here is selected for you.",
                      paths: [xcode.appendingPathComponent("Archives")], scope: .children, kind: .developer, selectedByDefault: false),
            CleanRule(id: "unavailable-simulators", category: .developer, title: "Unavailable simulators",
                      what: "Simulator devices whose runtime is no longer installed.",
                      why: "They cannot boot without their runtime. xcrun simctl delete unavailable removes the same devices.",
                      paths: [developer.appendingPathComponent("CoreSimulator/Devices")], scope: .unavailableSimulators, kind: .developer),
            CleanRule(id: "xcode-caches", category: .developer, title: "Xcode caches",
                      what: "Xcode's own caches: downloaded assets, the documentation index and the simulator's dyld caches.",
                      why: "Rebuilt or downloaded again as needed.",
                      paths: [caches.appendingPathComponent("com.apple.dt.Xcode"),
                              xcode.appendingPathComponent("DocumentationCache"),
                              developer.appendingPathComponent("CoreSimulator/Caches")],
                      scope: .folder, kind: .developer),
            CleanRule(id: "homebrew", category: .packageManagers, title: "Homebrew downloads",
                      what: "Bottles, casks and formula data Homebrew downloaded.",
                      why: "Homebrew downloads again whatever it needs. brew cleanup removes the same files.",
                      paths: [homebrewCache], scope: .children, kind: .toolCache),
            CleanRule(id: "npm", category: .packageManagers, title: "npm cache",
                      what: "Packages npm downloaded.",
                      why: "npm downloads them again on the next install.",
                      paths: [home.appendingPathComponent(".npm/_cacache")], scope: .folder, kind: .toolCache),
            CleanRule(id: "yarn", category: .packageManagers, title: "Yarn cache",
                      what: "Packages Yarn downloaded.",
                      why: "Yarn downloads them again on the next install.",
                      paths: [caches.appendingPathComponent("Yarn"), home.appendingPathComponent(".yarn/berry/cache")],
                      scope: .folder, kind: .toolCache),
            CleanRule(id: "pip", category: .packageManagers, title: "pip cache",
                      what: "Wheels and source archives pip downloaded, and pipx's build cache.",
                      why: "pip downloads them again on the next install.",
                      paths: [caches.appendingPathComponent("pip"), caches.appendingPathComponent("pipx"), home.appendingPathComponent(".cache/pip")],
                      scope: .folder, kind: .toolCache),
            CleanRule(id: "swiftpm", category: .packageManagers, title: "Swift Package Manager cache",
                      what: "Clones of package repositories and resolved manifests.",
                      why: "Fetched again the next time a package graph is resolved.",
                      paths: [caches.appendingPathComponent("org.swift.swiftpm")], scope: .folder, kind: .toolCache),
            CleanRule(id: "cocoapods", category: .packageManagers, title: "CocoaPods cache",
                      what: "Downloaded pods and the specs repository cache.",
                      why: "Downloaded again on the next pod install.",
                      paths: [caches.appendingPathComponent("CocoaPods")], scope: .folder, kind: .toolCache),
            CleanRule(id: "cargo", category: .packageManagers, title: "Cargo cache",
                      what: "Crate archives, their unpacked sources and git checkouts.",
                      why: "cargo downloads them again on the next build.",
                      paths: [".cargo/registry/cache", ".cargo/registry/src", ".cargo/git/checkouts"].map { home.appendingPathComponent($0) },
                      scope: .folder, kind: .toolCache),
            CleanRule(id: "gradle", category: .packageManagers, title: "Gradle cache",
                      what: "Downloaded dependencies and build caches.",
                      why: "Gradle downloads them again on the next build.",
                      paths: [home.appendingPathComponent(".gradle/caches")], scope: .folder, kind: .toolCache),
            CleanRule(id: "maven", category: .packageManagers, title: "Maven repository",
                      what: "Downloaded artifacts of every Maven build.",
                      why: "Maven downloads them again on the next build.",
                      paths: [home.appendingPathComponent(".m2/repository")], scope: .folder, kind: .toolCache),
            CleanRule(id: "go", category: .packageManagers, title: "Go caches",
                      what: "The build cache and downloaded modules.",
                      why: "go downloads and builds them again as needed.",
                      paths: [caches.appendingPathComponent("go-build"), home.appendingPathComponent("go/pkg/mod")],
                      scope: .folder, kind: .toolCache),
            CleanRule(id: "installers", category: .installers, title: "Installers in Downloads",
                      what: "Disk images and installer packages sitting in your Downloads folder.",
                      why: "The app is installed by now, or can be downloaded again. Nothing here is selected for you, in case one of them is a download you cannot repeat.",
                      paths: [home.appendingPathComponent("Downloads")], scope: .installers, kind: .downloads, selectedByDefault: false),
        ]
    }
}
