import Foundation

/// Names and identifiers that are never reported as leftovers, with the reason.
public struct ProtectionRules: Sendable {
    public var identifierPrefixes: [String: String]
    public var exactNames: [String: String]
    public var dotfileNames: [String: String]
    public var namePatterns: [(pattern: String, reason: String)]

    public init(identifierPrefixes: [String: String], exactNames: [String: String],
                dotfileNames: [String: String], namePatterns: [(pattern: String, reason: String)]) {
        self.identifierPrefixes = identifierPrefixes
        self.exactNames = exactNames
        self.dotfileNames = dotfileNames
        self.namePatterns = namePatterns
    }

    public static let standard = ProtectionRules(
        identifierPrefixes: [
            "com.apple.": "Part of macOS",
            "systemgroup.com.apple.": "Part of macOS",
            "com.revenuecat.": "Shared SDK storage used by several apps",
            "com.segment.": "Shared SDK storage used by several apps",
            "com.launchdarkly.": "Shared SDK storage used by several apps",
            "com.github.electron": "Shared by every Electron app",
            "org.sparkle-project.": "Sparkle updater, shared by several apps",
            "io.sentry": "Crash reporting SDK, shared by several apps",
            "com.plausiblelabs.": "Crash reporting SDK, shared by several apps",
            "com.crashlytics.": "Crash reporting SDK, shared by several apps",
            "com.google.firebase": "Shared SDK storage used by several apps",
            "com.microsoft.appcenter": "Shared SDK storage used by several apps",
            "com.bugsnag.": "Crash reporting SDK, shared by several apps",
            "com.qtproject": "Qt framework settings shared by Qt apps",
            "com.trolltech": "Qt framework settings shared by Qt apps",
            "org.cups.": "Printing system",
            "loginwindow": "Part of macOS",
            "org.swift.": "Swift toolchain",
            "is.workflow.": "Shortcuts",
            "com.googlecode.iterm2": "iTerm2",
        ],
        exactNames: [
            ".DS_Store": "Finder metadata",
            ".localized": "Finder metadata",
            "ByHost": "Preferences folder",
            "Fonts": "Fonts folder",
            "CrashReporter": "Crash report settings",
            "DiagnosticReports": "System crash logs",
            "CloudKit": "Part of macOS",
            "GeoServices": "Part of macOS",
            "PassKit": "Part of macOS",
            "GameKit": "Part of macOS",
            "FamilyCircle": "Part of macOS",
            "familycircled": "Part of macOS",
            "Animoji": "Part of macOS",
            "CallHistoryDB": "Part of macOS",
            "CallHistoryTransactions": "Part of macOS",
            "Knowledge": "Part of macOS",
            "MobileSync": "iPhone and iPad backups",
            "SyncServices": "Part of macOS",
            "DifferentialPrivacy": "Part of macOS",
            "AddressBook": "Contacts database",
            "CloudDocs": "iCloud Drive",
            "FileProvider": "Part of macOS",
            "DiskImages": "Part of macOS",
            "Assistant": "Siri",
            "Metadata": "Spotlight",
            "Spotlight": "Spotlight",
            "iLifeMediaBrowser": "Part of macOS",
            "ProApps": "Apple pro apps",
            "Apple": "Part of macOS",
            "App Store": "Part of macOS",
            "ApplePushService": "Part of macOS",
            "BTServer": "Part of macOS",
            "com.apple.TCC": "Privacy database",
            "livefsd": "Part of macOS",
            "Script Editor": "Part of macOS",
            "Audio": "Part of macOS",
            "DirectoryService": "Part of macOS",
            "OpenDirectory": "Part of macOS",
            "SystemConfiguration": "Part of macOS",
            "Logging": "Part of macOS",
            "Xsan": "Part of macOS",
            "Desktop Pictures": "Part of macOS",
            "ColorSync": "Part of macOS",
            "WindowServer": "Part of macOS",
            "hidfw-crashlogs": "Part of macOS",
            "Homebrew": "Homebrew",
            "pip": "Python package cache",
            "pipx": "Python package cache",
            "Python": "Python framework",
            "default.store": "Part of macOS",
            "default.store-shm": "Part of macOS",
            "default.store-wal": "Part of macOS",
            "WebPush": "Safari web push",
            "Databases": "WebKit storage",
            "virtualenv": "Python tooling",
            "no_backup": "Part of macOS",
            "pbs.plist": "Part of macOS",
            "MobileMeAccounts.plist": "iCloud account",
            "TokenBucketRateLimiter.plist": "Part of macOS",
            "ContextStoreAgent.plist": "Part of macOS",
            "diagnostics_agent.plist": "Part of macOS",
            "systemmigrationd.plist": "Part of macOS",
            "sharedfilelistd.plist": "Part of macOS",
            "replayd.plist": "Part of macOS",
            "mbuseragent.plist": "Part of macOS",
            "familycircled.plist": "Part of macOS",
            "installer_telemetry.plist": "Part of macOS",
            "icloudmailagent.plist": "iCloud Mail",
            "emaildefaults": "Part of macOS",
            "Avatar Cache Index.plist": "Part of macOS",
            "InstallHistory.plist": "Part of macOS",
            "InstalledPrinters.plist": "Printing",
            "LKDC-setup.log": "Part of macOS",
            "MCXTools.log": "Part of macOS",
            "fsck_hfs.log": "Part of macOS",
            "Baseband": "Part of macOS",
            "PrivacyPreservingMeasurement": "Part of macOS",
            "SiriTTSService": "Siri",
            "PhotosSearch.aapbz": "Photos",
            "DiagnosticReportsForNewHardware": "Part of macOS",
            "com.apple.CloudTelemetry": "Part of macOS",
            "com.apple.diagnosticextensionsd": "Part of macOS",
            "INSTALLATION": "Part of macOS",
            "iTunesLibrary.framework": "Part of macOS",
            "segment": "Shared SDK storage used by several apps",
            "SentryCrash": "Crash reporting SDK, shared by several apps",
            "RevenueCatFonts": "Shared SDK storage used by several apps",
            "RevenueCat": "Shared SDK storage used by several apps",
            "io.sentry": "Crash reporting SDK, shared by several apps",
            "MTLCompilerService": "Part of macOS",
            "Relocated Items": "macOS upgrade leftovers, review by hand",
            "SC Info": "Apple media DRM",
            "Library": "Shared library folder",
            "man": "Manual pages",
        ],
        dotfileNames: [
            ".ssh": "SSH keys and config",
            ".gnupg": "GPG keys",
            ".Trash": "Trash",
            ".CFUserTextEncoding": "Part of macOS",
            ".DS_Store": "Finder metadata",
            ".config": "Scanned per tool instead",
            ".local": "Scanned per tool instead",
            ".cache": "Scanned per tool instead",
            ".gitconfig": "Git",
            ".gitignore_global": "Git",
            ".git-credentials": "Git",
            ".zshrc": "Shell",
            ".zprofile": "Shell",
            ".zshenv": "Shell",
            ".zlogin": "Shell",
            ".zsh_history": "Shell",
            ".zsh_sessions": "Shell",
            ".bash_history": "Shell",
            ".bash_profile": "Shell",
            ".bashrc": "Shell",
            ".profile": "Shell",
            ".viminfo": "Vim",
            ".vimrc": "Vim",
            ".vim": "Vim",
            ".lesshst": "less",
            ".python_history": "Python",
            ".terminfo": "Terminal",
            ".oh-my-zsh": "Shell",
            ".npm": "npm cache",
            ".npmrc": "npm",
            ".yarnrc": "Yarn",
            ".cargo": "Rust",
            ".rustup": "Rust",
            ".docker": "Docker",
            ".kube": "Kubernetes",
            ".aws": "AWS CLI",
            ".swiftpm": "Swift Package Manager",
            ".homebrew": "Homebrew",
            ".claude": "Claude Code",
            ".claude.json": "Claude Code",
            ".cups": "Printing",
            ".fastlane": "fastlane",
            ".bundle": "Ruby bundler",
            ".gem": "Ruby gems",
            ".Xauthority": "X11",
            ".hushlogin": "Shell",
            ".editorconfig": "Editors",
            ".zcompdump": "Shell",
        ],
        namePatterns: [
            (#"^\.zcompdump"#, "Shell completion cache"),
            (#"^\.GlobalPreferences"#, "Global preferences"),
            (#"^Previously Relocated Items"#, "macOS upgrade leftovers, review by hand"),
            (#"^AAProfilePicture_"#, "Apple ID picture cache"),
            (#"^\.claude\.json"#, "Claude Code"),
            (#"^Uninst-[A-Za-z0-9]+\.log$"#, "Adobe uninstaller log"),
            (#"^regid\."#, "Software identification tag"),
            (#"^AAProfilePicture"#, "Apple ID picture cache"),
        ]
    )

    /// Owners of files whose names do not say who wrote them. Key is the file or folder name,
    /// value the normalized names of installed apps or formulae that own it.
    public static let knownOwners: [String: [String]] = [
        "NGL": ["adobeacrobat", "adobeacrobatreader", "adobecreativecloud", "adobe"],
        "AdobeGCInfo": ["adobeacrobat", "adobeacrobatreader", "adobecreativecloud", "adobe"],
        "Adobe": ["adobeacrobat", "adobeacrobatreader", "adobecreativecloud", "adobe"],
        "Google": ["googlechrome", "googledrive", "googleearth"],
        "Code": ["visualstudiocode"],
        "Cursor": ["cursor"],
        "Caches": ["tabby"],
        "G HUB": ["lghub", "logitechghub"],
        "Portable_SSD": ["samsungportablessd"],
        "Chromium": ["chromium"],
        "Vivaldi": ["vivaldi"],
        "Firefox": ["firefox"],
        "Mozilla": ["firefox", "thunderbird"],
        "BOINC": ["boincmanager"],
        "BOINC Data": ["boincmanager"],
        "Parallels": ["parallelsdesktop"],
        "JetBrains": ["intellijidea", "pycharm", "webstorm", "clion", "goland", "rider", "phpstorm", "rubymine", "datagrip", "androidstudio", "jetbrainstoolbox"],
        "Battle.net": ["battlenet"],
        "Steam": ["steam"],
        "obs-studio": ["obs"],
        "Dortania": ["opencorelegacypatcher"],
        "CoreSimulator": ["xcode"],
        "OVPNHelper.framework": ["openvpnconnect"],
        "OpenVPNConnect.framework": ["openvpnconnect"],
        "Xcode": ["xcode"],
        "Developer": ["xcode"],
        "DVTDownloads": ["xcode"],
        "XCTestDevices": ["xcode"],
        "node-gyp": ["node"],
        ".putty": ["filezilla", "putty"],
        ".android": ["androidstudio", "androidfiletransfer", "androidplatformtools", "adb"],
        ".m2": ["maven"],
        ".gradle": ["gradle", "androidstudio"],
        ".rubies": ["chruby", "rubyinstall"],
        ".vnc": ["vncviewer", "realvncviewer"],
        ".irssi": ["irssi"],
        ".ansible": ["ansible"],
        ".gsutil": ["googlecloudsdk", "gcloud"],
        ".DDLocalBackups": ["diskdrill"],
        ".DDPreview": ["diskdrill"],
        ".lmstudio": ["lmstudio"],
        ".lmstudio-home-pointer": ["lmstudio"],
        ".vscode": ["visualstudiocode", "code"],
        ".vscode-oss": ["vscodium"],
        ".vscode-oss-shared": ["vscodium"],
        ".cursor": ["cursor"],
        ".cursor-tutor": ["cursor"],
        ".codex": ["codex", "chatgpt"],
        ".dropbox": ["dropbox"],
        ".xpipe": ["xpipe"],
        ".clawdbot": ["clawdbot"],
        ".MSGViewer": ["msgviewer"],
    ]

    public static var dotfileOwners: [String: [String]] { knownOwners }

    public func reason(forName name: String, identifier: String?, location: LeftoverLocation) -> String? {
        if let reason = exactNames[name] { return reason }
        let rawLower = IdentifierParser.stripContainerPrefixes(name).lowercased()
        for (prefix, reason) in identifierPrefixes where rawLower.hasPrefix(prefix) { return reason }
        if let identifier {
            let lower = identifier.lowercased()
            for (prefix, reason) in identifierPrefixes where lower.hasPrefix(prefix) { return reason }
        }
        if !location.isDotfileArea, name.range(of: #"^[a-z_]+(d|agent)(\.plist)?$"#, options: .regularExpression) != nil {
            return "System daemon"
        }
        if location.kind == .dotfiles {
            if let reason = dotfileNames[name] { return reason }
        }
        for (pattern, reason) in namePatterns where name.range(of: pattern, options: .regularExpression) != nil {
            return reason
        }
        return nil
    }
}
